<?php $__env->startSection('title', 'Overview'); ?>
<?php $__env->startSection('content'); ?>
    <div class="flex flex-wrap items-end justify-between gap-5">
        <div><p class="eyebrow">Your content, at a glance</p><h1 class="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Welcome, <?php echo e(auth()->user()->name); ?>.</h1><p class="mt-3 text-stone-500">Keep your offers fresh and your readers inspired.</p></div>
        <a href="<?php echo e(route('admin.create', 'coupons')); ?>" class="admin-primary">+ Add coupon</a>
    </div>
    <div class="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $stats; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key => $stat): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?>
            <a href="<?php echo e(route('admin.index', $key)); ?>" class="rounded-2xl border border-stone-200 bg-white p-6 transition hover:border-emerald-400 hover:shadow-sm">
                <div class="flex justify-between text-sm font-bold text-stone-500"><span><?php echo e($stat['label']); ?></span><span class="text-emerald-700">↗</span></div>
                <div class="mt-5 text-4xl font-black tracking-tight"><?php echo e(number_format($stat['total'])); ?></div>
                <div class="mt-3 text-xs font-semibold text-emerald-700"><?php echo e(number_format($stat['published'])); ?> published <span class="text-stone-400">· <?php echo e(number_format($stat['total'] - $stat['published'])); ?> hidden</span></div>
            </a>
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?>
    </div>
    <div class="mt-7 grid gap-6 xl:grid-cols-[1fr_300px]">
        <section class="overflow-hidden rounded-2xl border border-stone-200 bg-white">
            <div class="flex items-center justify-between border-b border-stone-100 p-6"><h2 class="text-lg font-black">Recently updated offers</h2><a href="<?php echo e(route('admin.index', 'coupons')); ?>" class="text-sm font-bold text-emerald-800">View all →</a></div>
            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $recent; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $coupon): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?>
                <a href="<?php echo e(route('admin.edit', ['coupons', $coupon->id])); ?>" class="flex items-center justify-between gap-4 border-b border-stone-100 px-6 py-5 last:border-0 hover:bg-stone-50">
                    <div class="min-w-0"><p class="truncate text-sm font-bold"><?php echo e($coupon->title); ?></p><p class="mt-1 text-xs text-stone-500"><?php echo e($coupon->store->name); ?> · <?php echo e($coupon->updated_at->diffForHumans()); ?></p></div>
                    <span class="shrink-0 rounded-full px-2.5 py-1 text-xs font-semibold <?php echo e($coupon->is_active ? 'bg-emerald-50 text-emerald-800' : 'bg-stone-100 text-stone-500'); ?>"><?php echo e($coupon->is_active ? 'Published' : 'Hidden'); ?></span>
                </a>
            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?><p class="p-8 text-sm text-stone-500">No offers yet. Add your first coupon to get started.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
        </section>
        <aside class="space-y-5">
            <div class="rounded-2xl bg-emerald-950 p-6 text-white"><p class="text-sm font-semibold text-emerald-200">Offer interactions</p><p class="mt-4 text-4xl font-black"><?php echo e(number_format($clicks)); ?></p><p class="mt-3 text-sm leading-6 text-emerald-100/65">Total code reveals and tracked offer-link clicks.</p></div>
            <div class="rounded-2xl border border-stone-200 bg-white p-6"><h2 class="font-black">Create something new</h2><div class="mt-4 space-y-3"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = ['stores' => 'Add a store', 'categories' => 'Add a category', 'reviews' => 'Write an article']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><a class="block text-sm font-semibold text-emerald-800 hover:underline" href="<?php echo e(route('admin.create', $key)); ?>"><?php echo e($label); ?> →</a><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></div></div>
        </aside>
    </div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH /Applications/ServBay/www/couponhub/resources/views/admin/dashboard.blade.php ENDPATH**/ ?>