<?php $__env->startSection('title', 'Traffic & copies'); ?>
<?php $__env->startSection('content'); ?>
    <div><p class="eyebrow">Audience activity</p><h1 class="mt-3 text-3xl font-black tracking-tight">Traffic & copies</h1><p class="mt-2 text-stone-500">Explore page visits, article views, and successful coupon copies.</p></div>
    <div class="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 px-5 py-4 text-sm text-emerald-900">
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(config('analytics.enabled')): ?>
            <p>Activity from signed-in administrators is excluded. To test tracking, open the public website in a private/incognito window without signing in, view an article, and copy a coupon code. Copies count only when the clipboard action succeeds. Then refresh this page.</p>
        <?php else: ?>
            <p>Analytics tracking is currently disabled. New visits and coupon copies will not appear until tracking is enabled.</p>
        <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
    </div>

    <form method="GET" action="<?php echo e(route('admin.analytics')); ?>" class="mt-8 flex flex-wrap items-end gap-3 rounded-2xl border border-stone-200 bg-white p-5">
        <div><label for="from" class="admin-label">From</label><input type="date" id="from" name="from" value="<?php echo e($from); ?>" class="admin-input"></div>
        <div><label for="to" class="admin-label">To</label><input type="date" id="to" name="to" value="<?php echo e($to); ?>" class="admin-input"></div>
        <div><label for="event" class="admin-label">Activity type</label><select id="event" name="event" class="admin-input"><option value="">All activity</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = ['page_view' => 'Page view', 'review_view' => 'Article view', 'coupon_copy' => 'Coupon copy']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><option value="<?php echo e($value); ?>" <?php if(request('event') === $value): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></select></div>
        <div><label for="ip" class="admin-label">IP address</label><input id="ip" name="ip" value="<?php echo e(request('ip')); ?>" class="admin-input" placeholder="All IP addresses"></div>
        <div><label for="store_id" class="admin-label">Store</label><select id="store_id" name="store_id" class="admin-input"><option value="">All stores</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $stores; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $store): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><option value="<?php echo e($store->id); ?>" <?php if((string) request('store_id') === (string) $store->id): echo 'selected'; endif; ?>><?php echo e($store->name); ?></option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></select></div>
        <div><label for="country" class="admin-label">Country</label><select id="country" name="country" class="admin-input"><option value="">All countries</option><option value="unknown" <?php if(request('country') === 'unknown'): echo 'selected'; endif; ?>>Unknown</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $countries; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $country): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><option value="<?php echo e($country->country_code); ?>" <?php if(request('country') === $country->country_code): echo 'selected'; endif; ?>><?php echo e($country->country_name ?: $country->country_code); ?> (<?php echo e($country->country_code); ?>)</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></select></div>
        <button class="admin-primary">Filter</button><a href="<?php echo e(route('admin.analytics')); ?>" class="admin-secondary">Reset</a>
    </form>

    <p class="mt-5 text-sm text-stone-500">Totals and rankings follow the date, store, and country filters. Activity type and IP filters apply to the activity log.</p>
    <div class="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $stats; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $label => $total): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?>
            <div class="rounded-2xl border border-stone-200 bg-white p-6"><p class="text-sm font-bold text-stone-500"><?php echo e($label); ?></p><p class="mt-5 text-4xl font-black tracking-tight"><?php echo e(number_format($total)); ?></p></div>
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?>
    </div>

    <div class="mt-7 grid gap-6 lg:grid-cols-2">
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = ['Top articles' => $topReviews, 'Top copied coupons' => $topCoupons]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $heading => $items): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?>
            <section class="overflow-hidden rounded-2xl border border-stone-200 bg-white">
                <h2 class="border-b border-stone-100 p-6 text-lg font-black"><?php echo e($heading); ?></h2>
                <ol class="divide-y divide-stone-100">
                    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?>
                        <li class="flex items-center justify-between gap-4 px-6 py-4"><span class="min-w-0 break-words text-sm font-semibold"><?php echo e($item->title ?: 'Untitled'); ?></span><span class="shrink-0 text-sm font-bold text-emerald-800"><?php echo e(number_format($item->total)); ?> <?php echo e($heading === 'Top articles' ? 'views' : 'copies'); ?></span></li>
                    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?>
                        <li class="p-6 text-sm text-stone-500">No activity in this date range.</li>
                    <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                </ol>
            </section>
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?>
    </div>

    <p class="mt-5 text-sm text-stone-500">Country is estimated from the visitor’s IP. Local/private IP addresses and failed lookups appear as Unknown. <a href="https://db-ip.com" target="_blank" rel="noopener noreferrer" class="text-emerald-800 hover:underline">IP Geolocation by DB-IP</a>.</p>

    <section class="mt-7 overflow-hidden rounded-2xl border border-stone-200 bg-white">
        <h2 class="border-b border-stone-100 p-6 text-lg font-black">Activity log</h2>
        <div class="overflow-x-auto">
            <table class="w-full text-left text-sm">
                <thead class="border-b border-stone-100 bg-stone-50 text-xs uppercase tracking-wider text-stone-500"><tr><th class="px-6 py-4">Time</th><th class="px-6 py-4">Activity</th><th class="px-6 py-4">Page or coupon</th><th class="px-6 py-4">IP address</th><th class="px-6 py-4">Store</th><th class="px-6 py-4">Country</th></tr></thead>
                <tbody class="divide-y divide-stone-100">
                    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $logs; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $log): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?>
                        <tr><td class="whitespace-nowrap px-6 py-5 text-stone-500"><?php echo e($log->created_at->format('M j, Y H:i:s')); ?></td><td class="whitespace-nowrap px-6 py-5"><?php echo e(['page_view' => 'Page view', 'review_view' => 'Article view', 'coupon_copy' => 'Coupon copy'][$log->event] ?? $log->event); ?></td><td class="px-6 py-5"><p class="font-bold"><?php echo e($log->title); ?></p><p class="mt-1 break-all text-xs text-stone-500"><?php echo e($log->path); ?></p></td><td class="whitespace-nowrap px-6 py-5 text-stone-500"><?php echo e($log->ip ?? 'Unavailable'); ?></td><td class="px-6 py-5"><?php echo e($log->store?->name ?? '—'); ?></td><td class="whitespace-nowrap px-6 py-5 text-stone-500"><?php echo e($log->country_name ?? $log->country_code ?? 'Unknown'); ?></td></tr>
                    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?>
                        <tr><td colspan="6" class="p-12 text-center text-stone-500">No activity found. Try adjusting your filters.</td></tr>
                    <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                </tbody>
            </table>
        </div>
        <div class="border-t border-stone-100 p-5"><?php echo e($logs->links()); ?></div>
    </section>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH /Applications/ServBay/www/couponhub/resources/views/admin/analytics.blade.php ENDPATH**/ ?>