<?php $__env->startSection('title', ($item->exists ? 'Edit ' : 'Add ').$definition['singular']); ?>
<?php $__env->startSection('content'); ?>
    <a href="<?php echo e(route('admin.index', $resource)); ?>" class="text-sm font-bold text-emerald-800">← <?php echo e($definition['label']); ?></a>
    <h1 class="mt-5 text-3xl font-black tracking-tight"><?php echo e($item->exists ? 'Edit' : 'Add'); ?> <?php echo e($definition['singular']); ?></h1>
    <p class="mt-3 text-stone-500"><?php echo e($item->exists ? 'Update the details below, then save your changes.' : 'Create a new entry for your content library.'); ?></p>
    <form action="<?php echo e($item->exists ? route('admin.update', [$resource, $item->id]) : route('admin.store', $resource)); ?>" method="POST" enctype="multipart/form-data" class="mt-7 max-w-4xl rounded-2xl border border-stone-200 bg-white p-6 sm:p-8">
        <?php echo csrf_field(); ?>
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($item->exists): ?> <?php echo method_field('PUT'); ?> <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
        <div class="grid gap-6 sm:grid-cols-2">
            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $definition['fields']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $field => $spec): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?>
                <?php
                    [$label, $type] = array_pad(explode('|', $spec), 2, 'text');
                    $value = old($field, $item->{$field});
                    if ($value instanceof \DateTimeInterface) $value = $value->format('Y-m-d\TH:i');
                    $required = $field === $definition['title'] || ($field === 'store_id' && $resource === 'coupons') || $field === 'content';
                ?>
                <div class="<?php echo e(in_array($type, ['textarea', 'categories', 'image']) ? 'sm:col-span-2' : ''); ?>">
                    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($type === 'checkbox'): ?>
                        <input type="hidden" name="<?php echo e($field); ?>" value="0">
                        <label class="flex items-center gap-3 rounded-xl border border-stone-200 px-4 py-3 text-sm font-semibold"><input type="checkbox" name="<?php echo e($field); ?>" value="1" <?php if($value): echo 'checked'; endif; ?> class="size-4 accent-emerald-800"><?php echo e($label); ?></label>
                    <?php else: ?>
                        <label for="<?php echo e($field); ?>" class="admin-label"><?php echo e($label); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($required): ?><span class="text-red-600"> *</span><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></label>
                        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($type === 'image'): ?>
                            <div data-image-picker class="rounded-xl border border-dashed border-stone-300 p-4">
                                <img data-image-preview src="<?php echo e(\App\Support\Media::url($item->{$field})); ?>" alt="Current <?php echo e($label); ?>" class="mb-4 h-36 max-w-full rounded-lg object-contain" <?php if(!\App\Support\Media::url($item->{$field})): ?> hidden <?php endif; ?>>
                                <input id="<?php echo e($field); ?>" name="<?php echo e($field); ?>_upload" type="file" accept="image/jpeg,image/png,image/webp" data-image-input class="admin-input">
                                <p class="mt-2 text-xs text-stone-500">JPG, PNG or WebP · Up to 5 MB · Maximum 6000 × 6000 px. Select again if the form has validation errors.</p>
                                <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(config('media.driver') === 'cloudinary'): ?><p class="mt-2 text-xs text-emerald-800">Uploaded images are saved to Cloudinary as optimized WebP.</p><?php else: ?><p class="mt-2 text-xs text-emerald-800">Uploaded images are resized and saved as WebP on this server.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                                <label class="admin-label mt-4" for="<?php echo e($field); ?>_url">Or use an image URL</label>
                                <input id="<?php echo e($field); ?>_url" name="<?php echo e($field); ?>" type="url" value="<?php echo e(old($field, str_starts_with($item->{$field} ?? '', 'uploads/') ? '' : $item->{$field})); ?>" class="admin-input" placeholder="https://…">
                                <p class="mt-2 text-xs text-stone-500">A selected file takes priority over the URL.</p>
                                <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($item->{$field}): ?><label class="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" name="<?php echo e($field); ?>_remove" value="1" <?php if(old($field.'_remove')): echo 'checked'; endif; ?>> Remove current image</label><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                                <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__errorArgs = [$field.'_upload'];
$__bag = $errors->getBag($__errorArgs[1] ?? 'default');
if ($__bag->has($__errorArgs[0])) :
if (isset($message)) { $__messageOriginal = $message; }
$message = $__bag->first($__errorArgs[0]); ?><p class="mt-2 text-sm text-red-700"><?php echo e($message); ?></p><?php unset($message);
if (isset($__messageOriginal)) { $message = $__messageOriginal; }
endif;
unset($__errorArgs, $__bag); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                            </div>
                        <?php elseif($type === 'textarea'): ?>
                            <textarea id="<?php echo e($field); ?>" name="<?php echo e($field); ?>" rows="<?php echo e($field === 'content' ? 14 : 3); ?>" class="admin-input" <?php if($field === 'content'): ?> data-review-editor data-upload-url="<?php echo e(route('admin.images.store')); ?>" data-format="<?php echo e(old('content_format', $item->content_format ?? 'text')); ?>" <?php endif; ?> <?php if($required): echo 'required'; endif; ?>><?php echo e($field === 'content' && old('content_format', $item->content_format) === 'html' ? \App\Support\ReviewContent::sanitize($value ?? '') : $value); ?></textarea>
                            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($field === 'content'): ?><input type="hidden" name="content_format" value="<?php echo e(old('content_format', $item->content_format ?? 'text')); ?>"><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                        <?php elseif(in_array($type, ['store', 'category', 'offer_type', 'article_type', 'categories'])): ?>
                            <?php
                                $options = match($type) {
                                    'store' => $stores->pluck('name', 'id'),
                                    'category', 'categories' => $categories->pluck('name', 'id'),
                                    'offer_type' => ['code' => 'Coupon code', 'deal' => 'Online deal'],
                                    'article_type' => ['review' => 'Review', 'guide' => 'Guide'],
                                };
                                $selected = $type === 'categories' ? old('category_ids', session()->hasOldInput() ? [] : ($item->exists ? $item->categories->modelKeys() : [])) : [$value];
                            ?>
                            <select id="<?php echo e($field); ?>" name="<?php echo e($field); ?><?php echo e($type === 'categories' ? '[]' : ''); ?>" class="admin-input" <?php if($type === 'categories'): ?> multiple size="5" <?php endif; ?> <?php if($required): echo 'required'; endif; ?>>
                                <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(in_array($type, ['store', 'category'])): ?><option value=""><?php echo e($required ? 'Choose an option' : 'None'); ?></option><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                                <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $options; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $optionValue => $optionLabel): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><option value="<?php echo e($optionValue); ?>" <?php if(in_array($optionValue, (array) $selected)): echo 'selected'; endif; ?>><?php echo e($optionLabel); ?></option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?>
                            </select>
                            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($type === 'categories'): ?><p class="mt-2 text-xs text-stone-500">Hold Command (Mac) or Ctrl (Windows) to select multiple categories.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                        <?php else: ?>
                            <input id="<?php echo e($field); ?>" name="<?php echo e($field); ?>" type="<?php echo e($type); ?>" value="<?php echo e($value); ?>" class="admin-input" <?php if($required): echo 'required'; endif; ?> <?php if($type === 'number'): ?> min="0" step="<?php echo e($field === 'rating' ? '0.1' : '1'); ?>" <?php endif; ?> <?php if($field === 'rating'): ?> max="5" <?php endif; ?>>
                        <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($field === 'slug'): ?><p class="mt-2 text-xs text-stone-500">Leave blank to generate from the name or title. Use lowercase letters, numbers and hyphens.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($field === 'affiliate_url'): ?><p class="mt-2 text-xs text-stone-500">Paste your full affiliate URL, including tracking parameters. Shows a highlighted offer above and below the article. Leave empty to hide it.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($field === 'content'): ?><p class="mt-2 text-xs text-stone-500">Add headings, images with captions, comparison tables and quotes. Double-click an image or table to edit or remove it.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                    <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__errorArgs = [$field];
$__bag = $errors->getBag($__errorArgs[1] ?? 'default');
if ($__bag->has($__errorArgs[0])) :
if (isset($message)) { $__messageOriginal = $message; }
$message = $__bag->first($__errorArgs[0]); ?><p class="mt-2 text-sm text-red-700"><?php echo e($message); ?></p><?php unset($message);
if (isset($__messageOriginal)) { $message = $__messageOriginal; }
endif;
unset($__errorArgs, $__bag); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                </div>
            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?>
        </div>
        <div class="mt-8 flex flex-wrap items-center gap-3 border-t border-stone-100 pt-6"><button class="admin-primary">Save <?php echo e($definition['singular']); ?></button><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($resource === 'reviews' && $item->exists): ?><a class="admin-secondary" href="<?php echo e(route('admin.reviews.preview', $item->id)); ?>" target="_blank" rel="noopener">Preview saved article ↗</a><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?><a href="<?php echo e(route('admin.index', $resource)); ?>" class="admin-secondary">Cancel</a><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($item->exists): ?><a href="<?php echo e(route('admin.confirm-delete', [$resource, $item->id])); ?>" class="ml-auto text-sm font-semibold text-red-700">Delete <?php echo e($definition['singular']); ?></a><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div>
    </form>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH /Applications/ServBay/www/couponhub/resources/views/admin/form.blade.php ENDPATH**/ ?>