<?php $__env->startSection('title', $definition['label']); ?>
<?php $__env->startSection('content'); ?>
    <div class="flex flex-wrap items-center justify-between gap-4"><div><p class="eyebrow">Content library</p><h1 class="mt-3 text-3xl font-black tracking-tight"><?php echo e($definition['label']); ?></h1><p class="mt-2 text-stone-500">Create, organize, and publish your <?php echo e(strtolower($definition['label'])); ?>.</p></div><a href="<?php echo e(route('admin.create', $resource)); ?>" class="admin-primary">+ Add <?php echo e($definition['singular']); ?></a></div>
    <div class="mt-8 overflow-hidden rounded-2xl border border-stone-200 bg-white">
        <form method="GET" action="<?php echo e(route('admin.index', $resource)); ?>" class="flex flex-wrap items-end gap-3 border-b border-stone-100 p-5">
            <div class="min-w-0 flex-1"><label for="q" class="admin-label">Search <?php echo e(strtolower($definition['label'])); ?></label><input id="q" name="q" value="<?php echo e(request('q')); ?>" class="admin-input" placeholder="Search by <?php echo e($definition['title']); ?>…"></div>
            <div><label for="status" class="admin-label">Status</label><select id="status" name="status" class="admin-input"><option value="">All statuses</option><option value="published" <?php if(request('status') === 'published'): echo 'selected'; endif; ?>>Published</option><option value="hidden" <?php if(request('status') === 'hidden'): echo 'selected'; endif; ?>>Hidden</option></select></div>
            <button class="admin-secondary">Filter</button>
            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(request()->filled('q') || request()->filled('status')): ?><a href="<?php echo e(route('admin.index', $resource)); ?>" class="admin-secondary">Reset</a><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
        </form>
        <div class="overflow-x-auto">
            <table class="w-full text-left text-sm">
                <thead class="border-b border-stone-100 bg-stone-50 text-xs uppercase tracking-wider text-stone-500"><tr><th class="px-6 py-4"><?php echo e(ucfirst($definition['title'])); ?></th><th class="px-6 py-4">Status</th><th class="px-6 py-4">Updated</th><th class="px-6 py-4 text-right">Actions</th></tr></thead>
                <tbody class="divide-y divide-stone-100">
                    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?>
                        <tr class="hover:bg-stone-50/60"><td class="min-w-60 px-6 py-5"><?php ($thumbnail = $resource === 'stores' ? $item->logo_url : ($resource === 'reviews' ? $item->image_url : null)); ?>
                        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($thumbnail): ?><img src="<?php echo e($thumbnail); ?>" alt="<?php echo e($item->{$definition['title']}); ?>" loading="lazy" width="56" height="56" class="float-left mr-3 size-14 rounded-xl border border-stone-200 object-cover"><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?><a href="<?php echo e(route('admin.edit', [$resource, $item->id])); ?>" class="font-bold hover:text-emerald-800"><?php echo e($item->{$definition['title']}); ?></a><div class="mt-1 text-xs text-stone-400"><?php echo e($item->slug); ?></div></td><td class="px-6 py-5"><span class="rounded-full px-2.5 py-1 text-xs font-bold <?php echo e($item->is_active ? 'bg-emerald-50 text-emerald-800' : 'bg-stone-100 text-stone-500'); ?>"><?php echo e($item->is_active ? 'Published' : 'Hidden'); ?></span></td><td class="whitespace-nowrap px-6 py-5 text-stone-500"><?php echo e($item->updated_at->format('M j, Y')); ?></td><td class="whitespace-nowrap px-6 py-5 text-right"><a href="<?php echo e(route('admin.edit', [$resource, $item->id])); ?>" class="font-bold text-emerald-800">Edit</a><a href="<?php echo e(route('admin.confirm-delete', [$resource, $item->id])); ?>" class="ml-4 text-stone-400 hover:text-red-700">Delete</a></td></tr>
                    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?><tr><td colspan="4" class="p-12 text-center text-stone-500">No items found. Adjust your filters or add a new <?php echo e($definition['singular']); ?>.</td></tr><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
                </tbody>
            </table>
        </div>
        <div class="border-t border-stone-100 p-5"><?php echo e($items->links()); ?></div>
    </div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH /Applications/ServBay/www/couponhub/resources/views/admin/index.blade.php ENDPATH**/ ?>